version: "3.8"

services:
  spark-master:
    build: .
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_DAEMON_JAVA_OPTS=-Dlog4j2.disable.jmx=true
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - spark-network
    volumes:
      - ./jobs:/jobs  # <-- This mounts your local jobs/ folder to /jobs inside the container

  spark-worker-1:
    build: .
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - "8081:8081"  # Worker 1 UI
    networks:
      - spark-network

  spark-worker-2:
    build: .
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - "8082:8081"  # Worker 2 UI, avoid conflicts
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
